# Site Config
name: "IBM Makes"
description: Making at IBM
baseurl: "/ibm-studios/makers"
url: pages.github.ibm.com/ibm-studios/makers

# Build Settings
markdown: kramdown
highlighter: true
permalink: /blog/:title.html

# In/ Excludes
include: [".htaccess"]
exclude: ["node_modules", "gulpfile.js", "Gemfile", "Gemfile.lock", ".jekyll-metadata", "commit-hook.sh", "package.json", "local_config.yml", "README.md", "package-lock.json"]

# Plugins
assets:
  digest: true
  cache: false
  sources:
    - "_site/assets"

# Read and Output Collections
collections:
  projects:
    output: true
    permalink: projects/:path/
  events:
    output: true
    permalink: events/:path/
